blueprint:

  name: ZHA - Tuya - TS004F Rotating Knob - Custom Actions

  description: >-
    This automation adds triggers for all actions of the Tuya TS004F rotating knob remote.
    It provides simple custom actions for five basic commands:
    
    - Short press
    - Long press
    - Double press
    - Rotate left
    - Rotate right
    
    For each command type, you can define your own custom action to control any entity
    or perform any action in Home Assistant.

    Sold on AliExpress by brands like Moes, Girier etc.

  domain: automation

  input:
    remote:
      name: Tuya - TS004F Rotating Knob
      description: Select the remote control you wish to use.
      selector:
        device:
          integration: zha
          manufacturer: _TZ3000_4fjiwweb
          model: TS004F
    press_short:
      name: Short Press
      description: Action to perform when button is pressed once
      selector:
        action:
      default: []
    press_double:
      name: Double Press
      description: Action to perform when button is double-pressed
      selector:
        action:
      default: []
    press_long:
      name: Long Press
      description: Action to perform when button is long-pressed
      selector:
        action:
      default: []
    rotate_left:
      name: Rotate Left
      description: Action to perform when rotating counter-clockwise (step down)
      selector:
        action:
      default: []
    rotate_right:
      name: Rotate Right
      description: Action to perform when rotating clockwise (step up)
      selector:
        action:
      default: []

mode: restart
max_exceeded: silent

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote

action:
  - variables:
      command: "{{ trigger.event.data.command }}"
      cluster_id: "{{ trigger.event.data.cluster_id }}"
      endpoint_id: "{{ trigger.event.data.endpoint_id }}"
      args: "{{ trigger.event.data.args }}"

  - choose:
    # Short Press
    - conditions:
        - "{{ command == 'toggle' or command == 'remote_button_short_press' }}"
      sequence: !input press_short

    # Double Press
    - conditions:
        - "{{ command == 'remote_button_double_press' }}"
      sequence: !input press_double

    # Long Press
    - conditions:
        - "{{ command == 'remote_button_long_press' }}"
      sequence: !input press_long

    # Rotate Left (Step Down)
    - conditions:
        - "{{ command == 'left' or (command == 'step' and args[0] == 1) }}"
      sequence: !input rotate_left

    # Rotate Right (Step Up)
    - conditions:
        - "{{ command == 'right' or (command == 'step' and args[0] == 0) }}"
      sequence: !input rotate_right