blueprint:

  name: ZHA - Tuya - TS004F Rotating Knob - Custom Actions

  description: >-
    This automation adds triggers for all actions of the Tuya TS004F rotating knob remote.
    It can be used in both Command/Dimmer and Event/Scene mode. Both modes have their own actions.

    In Command/Dimmer mode the config is mostly internal except for pressing the button.
    In Event/Scene mode you can select your own actions.
    To switch modes you can press the button 3 times fast.

    Sold on AliExpress by brands like Moes, Girier etc.

  domain: automation

  input:
    mode:
    max:
          # Removed mode selection and max queue
    remote:
      name: Tuya - TS004F Rotating Knob
      description: Select the remote control you wish to use.
      selector:
        device:
          integration: zha
          manufacturer: _TZ3000_4fjiwweb
          model: TS004F
  # Removed light and toggle inputs
    press_short:
    press_double:
    press_long:
    rotate_left:
    rotate_right:
          # Removed all Event/Scene mode actions

mode: !input mode
max: !input max
max_exceeded: silent

trigger:
  # Removed all Event/Scene mode actions
    # Event mode: Double Press
    - conditions:
        - "{{ command == 'remote_button_double_press' }}"
      sequence: !input press_double

    # Event mode: Long Press
    - conditions:
        - "{{ command == 'remote_button_long_press' }}"
      sequence: !input press_long

    # Event mode: Rotate Left
    - conditions:
        - "{{ command == 'left' }}"
      sequence: !input rotate_left

    # Event mode: Rotate Right
    - conditions:
        - "{{ command == 'right' }}"
      sequence: !input rotate_right
